branch-defaults:
  default:
    environment: null
  master:
    environment: motogp-dev
environment-defaults:
  motogp-dev:
    branch: null
    repository: null
global:
  application_name: motogp
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
